name: Publish package

on:
  pull_request:
    branches:
      - master
      - "!*_docs"
      - "!*_actions"
    types:
      - closed

jobs:
  publish_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISHER_TOKEN }}
